import asyncio
import requests

from loguru import logger
from pipecat_flows import (
    FlowArgs,
    FlowManager,
    FlowsFunctionSchema,
    NodeConfig,
)


ICS_SEARCH_API = "https://sacs-backend.vibhohcm.com/api/knowledge/search"


SYSTEM_PROMPT = """
You are a friendly and professional AI voice agent for
Indian Consulate Services.

You are making an OUTBOUND phone call.

The customer did not call you. You called the customer.

Customer name:
{customer_name}

Reason for the call:
{outbound_message}


IMPORTANT CONVERSATION RULES
----------------------------

Speak naturally like a human customer-service representative.

Keep responses short and suitable for a phone conversation.

Do not sound robotic.

Do not repeatedly greet the customer.

Do not ask "How can I help you today?" because YOU initiated
the outbound call.


OUTBOUND GREETING
-----------------

When the customer answers, introduce yourself and explain why
you are calling.

The first response must be generated by the LLM.

Do NOT use a hard-coded greeting.


ICS INFORMATION
---------------

If the customer asks a factual question about Indian Consulate
Services, use the search_ics tool.

Examples:

- passport
- visa
- PCC
- police clearance certificate
- OCI
- required documents
- fees
- processing time
- appointments
- application status
- collection
- office information
- procedures
- other ICS services


SEARCH RULE
-----------

When the customer asks an ICS factual question:

1. Call search_ics.
2. Wait for the result.
3. Treat the result as the factual source.
4. Explain the result naturally to the customer.

Do not invent information.

Do not guess fees, documents, dates, requirements,
processing times or procedures.

Do not mention the search tool, API, database or
knowledge base to the customer.


IF INFORMATION IS NOT FOUND
---------------------------

If search_ics does not return reliable information,
tell the customer that you do not have reliable information
about that question at the moment.

Do not make up an answer.


NATURAL CONVERSATION
--------------------

If the customer says "yes", "okay", "alright", etc.,
continue the conversation naturally.

If the customer asks you to repeat something, repeat it briefly.

If the customer is busy, politely ask whether they would
like a callback later.

If the customer wants to end the conversation, politely
say goodbye.


VOICE STYLE
-----------

Be:

- friendly
- professional
- concise
- patient
- natural

Avoid long paragraphs.

Speak as a voice agent, not as a text chatbot.
"""


async def initialize_user(flow_manager: FlowManager):
    """
    Initialize state for the outbound conversation.
    """

    flow_manager.state["customer_name"] = (
        flow_manager.state.get("customer_name", "")
    )

    flow_manager.state["phone_number"] = (
        flow_manager.state.get("phone_number", "")
    )

    flow_manager.state["outbound_message"] = (
        flow_manager.state.get(
            "outbound_message",
            "We are calling regarding your application.",
        )
    )

    flow_manager.state["last_user_text"] = ""

    logger.info("Outbound flow state initialized.")


async def search_ics(
    args: FlowArgs,
    flow_manager: FlowManager,
):
    """
    Search the ICS knowledge service.

    IMPORTANT:
    This function does NOT call another LLM.

    The search result is returned directly to the SAME LLM
    that called this function.

    Qwen then converts the result into a natural response.
    """

    query = (
        args.get("query")
        or args.get("question")
        or ""
    ).strip()

    if not query:
        query = (
            flow_manager.state.get(
                "last_user_text",
                "",
            )
        ).strip()

    if not query:
        return (
            {
                "status": "error",
                "message": "No customer question was provided.",
            },
            None,
        )

    logger.info(f"ICS search: {query}")

    try:
        loop = asyncio.get_running_loop()

        def make_request():
            response = requests.post(
                ICS_SEARCH_API,
                json={
                    "query": query,
                },
                headers={
                    "Content-Type": "application/json",
                },
                timeout=30,
            )

            response.raise_for_status()
            return response.json()

        result = await loop.run_in_executor(
            None,
            make_request,
        )

        logger.info(f"ICS search result: {result}")

        if not result.get("success", False):
            return (
                {
                    "status": "not_found",
                    "message": (
                        "No reliable information was found "
                        "for this question."
                    ),
                },
                None,
            )

        answer = result.get(
            "answer",
            "",
        )

        service = result.get(
            "service",
            "",
        )

        if not answer:
            return (
                {
                    "status": "not_found",
                    "message": (
                        "No specific information was found "
                        "for this question."
                    ),
                },
                None,
            )

        return (
            {
                "status": "success",
                "service": service,
                "answer": answer,
            },
            None,
        )

    except requests.exceptions.Timeout:
        logger.error("ICS API timeout.")

        return (
            {
                "status": "error",
                "message": (
                    "The information service is temporarily "
                    "unavailable."
                ),
            },
            None,
        )

    except requests.exceptions.RequestException as exc:
        logger.error(f"ICS API error: {exc}")

        return (
            {
                "status": "error",
                "message": (
                    "The information service is temporarily "
                    "unavailable."
                ),
            },
            None,
        )

    except Exception as exc:
        logger.exception(f"Unexpected search error: {exc}")

        return (
            {
                "status": "error",
                "message": (
                    "The information service encountered "
                    "an error."
                ),
            },
            None,
        )


async def end_conversation(
    args: FlowArgs,
    flow_manager: FlowManager,
):
    """
    End the conversation when the customer wants to finish.
    """

    logger.info("Customer requested conversation end.")

    return (
        {
            "message": (
                "Thank you for your time. "
                "Have a great day. Goodbye."
            ),
        },
        None,
    )


def create_initial_node(
    customer_name: str,
    outbound_message: str,
) -> NodeConfig:
    """
    Create the initial outbound conversation node.

    The greeting is generated by Qwen.

    There is NO hard-coded TextFrame greeting.
    """

    system_prompt = SYSTEM_PROMPT.format(
        customer_name=customer_name,
        outbound_message=outbound_message,
    )

    first_message = (
        "The customer has just answered the outbound call. "
        "Start the conversation now. "
        "Greet the customer naturally, introduce yourself "
        "as Indian Consulate Services, explain the reason "
        "for the call, and ask one short follow-up question. "
        "Keep it brief and natural."
    )

    if customer_name:
        first_message += (
            f" The customer's name is {customer_name}. "
            "Use their name naturally."
        )

    return NodeConfig(
        system_prompt=system_prompt,

        task_messages=[
            {
                "role": "user",
                "content": first_message,
            }
        ],

        functions=[
            FlowsFunctionSchema(
                name="search_ics",
                description=(
                    "Search the authoritative ICS information "
                    "service. Use this whenever the customer "
                    "asks a factual question about an ICS service."
                ),
                handler=search_ics,
                properties={
                    "query": {
                        "type": "string",
                        "description": (
                            "The customer's factual question "
                            "about Indian Consulate Services."
                        ),
                    }
                },
                required=["query"],
            ),

            FlowsFunctionSchema(
                name="end_conversation",
                description=(
                    "End the conversation when the customer "
                    "clearly wants to finish the call."
                ),
                handler=end_conversation,
                properties={},
                required=[],
            ),
        ],

        respond_immediately=True,
    )